#!/bin/bash

REPOS="CSDL2 SDL2 Ccairo Cairo spline"

for r in $REPOS
do
    if [ -d "modules/${r}" ]; then
        cd "modules/${r}" && git pull origin master && cd ../..
    else
        git clone git@github.com:${1}/${r}.swift.git modules/${r}
    fi
done

